name: Deploy Test two-way autodeploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.TWO_WAY_AUTODEPLOY_HOST }}
          username: ${{ secrets.TWO_WAY_AUTODEPLOY_USER }}
          key: ${{ secrets.TWO_WAY_AUTODEPLOY_KEY }}
          script: |
            #Переключаемся в нужную папку
            cd ~/vasilyevr.beget.tech/public_html
            
            #Клинируем репозиторий в папку (только для первой выгрузки!!!)
            #git clone https://github.com/site100ru/test-two-way-autodeploy.git .
            
            #Клинируем репозиторий в папку
            git pull
            
            #Если кто то изменил файлы на сервере минуя GitHub, перезаписываем версию на сервере из GitHub
            #git reset --hard HEAD
            #git pull origin main
